# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebAPI/account_authorization_2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import shared_1_pb2 as common_dot_shared__1__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$WebAPI/account_authorization_2.proto\x12\x17\x61\x63\x63ount_authorization_2\x1a\x15\x63ommon/shared_1.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n\x0c\x41\x63\x63ountLogon\x12\x12\n\naccount_id\x18\x01 \x02(\x11\x12\x10\n\x08username\x18\x02 \x02(\t\x12\x10\n\x08password\x18\x03 \x02(\t\"\xaa\x02\n\x12\x41\x63\x63ountLogonResult\x12\x12\n\naccount_id\x18\x01 \x02(\x11\x12\x13\n\x0bresult_code\x18\x02 \x02(\r\x12$\n\x0ctext_message\x18\x03 \x01(\x0b\x32\x0e.shared_1.Text\x12\x38\n\x14server_utc_timestamp\x18\x04 \x02(\x0b\x32\x1a.google.protobuf.Timestamp\"\x8a\x01\n\nResultCode\x12\x17\n\x13RESULT_CODE_SUCCESS\x10\x00\x12(\n$RESULT_CODE_PASSWORD_CHANGE_REQUIRED\x10\x01\x12 \n\x1cRESULT_CODE_PASSWORD_EXPIRED\x10\x02\x12\x17\n\x13RESULT_CODE_FAILURE\x10\x65\"W\n\x15\x41\x63\x63ountPasswordChange\x12\x12\n\naccount_id\x18\x01 \x02(\x11\x12\x14\n\x0cold_password\x18\x02 \x02(\t\x12\x14\n\x0cnew_password\x18\x03 \x02(\t\"\xac\x01\n\x1b\x41\x63\x63ountPasswordChangeResult\x12\x12\n\naccount_id\x18\x01 \x02(\x11\x12\x13\n\x0bresult_code\x18\x02 \x02(\r\x12$\n\x0ctext_message\x18\x03 \x01(\x0b\x32\x0e.shared_1.Text\">\n\nResultCode\x12\x17\n\x13RESULT_CODE_SUCCESS\x10\x00\x12\x17\n\x13RESULT_CODE_FAILURE\x10\x65\"#\n\rAccountLogoff\x12\x12\n\naccount_id\x18\x01 \x02(\x11\"\xde\x01\n\x13\x41\x63\x63ountLogoffResult\x12\x12\n\naccount_id\x18\x01 \x02(\x11\x12\x13\n\x0bresult_code\x18\x02 \x02(\r\x12$\n\x0ctext_message\x18\x03 \x01(\x0b\x32\x0e.shared_1.Text\x12\x38\n\x14server_utc_timestamp\x18\x04 \x02(\x0b\x32\x1a.google.protobuf.Timestamp\">\n\nResultCode\x12\x17\n\x13RESULT_CODE_SUCCESS\x10\x00\x12\x17\n\x13RESULT_CODE_FAILURE\x10\x65')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WebAPI.account_authorization_2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCOUNTLOGON._serialized_start=121
  _ACCOUNTLOGON._serialized_end=191
  _ACCOUNTLOGONRESULT._serialized_start=194
  _ACCOUNTLOGONRESULT._serialized_end=492
  _ACCOUNTLOGONRESULT_RESULTCODE._serialized_start=354
  _ACCOUNTLOGONRESULT_RESULTCODE._serialized_end=492
  _ACCOUNTPASSWORDCHANGE._serialized_start=494
  _ACCOUNTPASSWORDCHANGE._serialized_end=581
  _ACCOUNTPASSWORDCHANGERESULT._serialized_start=584
  _ACCOUNTPASSWORDCHANGERESULT._serialized_end=756
  _ACCOUNTPASSWORDCHANGERESULT_RESULTCODE._serialized_start=694
  _ACCOUNTPASSWORDCHANGERESULT_RESULTCODE._serialized_end=756
  _ACCOUNTLOGOFF._serialized_start=758
  _ACCOUNTLOGOFF._serialized_end=793
  _ACCOUNTLOGOFFRESULT._serialized_start=796
  _ACCOUNTLOGOFFRESULT._serialized_end=1018
  _ACCOUNTLOGOFFRESULT_RESULTCODE._serialized_start=694
  _ACCOUNTLOGOFFRESULT_RESULTCODE._serialized_end=756
# @@protoc_insertion_point(module_scope)
