# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebAPI/instrument_definition_2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WebAPI import metadata_2_pb2 as WebAPI_dot_metadata__2__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$WebAPI/instrument_definition_2.proto\x12\x17instrument_definition_2\x1a\x17WebAPI/metadata_2.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x02\n\x14InstrumentDefinition\x12\"\n\x1aunderlying_contract_symbol\x18\x01 \x01(\t\x12\x1b\n\x13\x63qg_instrument_type\x18\x02 \x01(\r\x12\x36\n\x12maturity_timestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12 \n\x18\x65xchange_instrument_type\x18\x04 \x01(\t\x12\x19\n\x11settlement_method\x18\x05 \x01(\r\x12\x0e\n\x06strike\x18\x06 \x01(\x01\x12\x16\n\x0e\x65xercise_style\x18\x07 \x01(\r\x12\x1a\n\x12pricing_convention\x18\x08 \x01(\r\"\x7f\n\x1bInstrumentDefinitionRequest\x12L\n\x15instrument_definition\x18\x01 \x01(\x0b\x32-.instrument_definition_2.InstrumentDefinition\x12\x12\n\naccount_id\x18\x02 \x01(\x11\"U\n\x1aInstrumentDefinitionReport\x12\x37\n\x11\x63ontract_metadata\x18\x01 \x01(\x0b\x32\x1c.metadata_2.ContractMetadata')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WebAPI.instrument_definition_2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTRUMENTDEFINITION._serialized_start=124
  _INSTRUMENTDEFINITION._serialized_end=396
  _INSTRUMENTDEFINITIONREQUEST._serialized_start=398
  _INSTRUMENTDEFINITIONREQUEST._serialized_end=525
  _INSTRUMENTDEFINITIONREPORT._serialized_start=527
  _INSTRUMENTDEFINITIONREPORT._serialized_end=612
# @@protoc_insertion_point(module_scope)
