# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/decimal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ommon/decimal.proto\x12\x03\x63qg\"6\n\x07\x44\x65\x63imal\x12\x16\n\x0bsignificand\x18\x01 \x01(\x12:\x01\x30\x12\x13\n\x08\x65xponent\x18\x02 \x01(\x11:\x01\x30\x42\x0e\x42\x0c\x44\x65\x63imalProto')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.decimal_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\014DecimalProto'
  _DECIMAL._serialized_start=29
  _DECIMAL._serialized_end=83
# @@protoc_insertion_point(module_scope)
